### ISSUE TITLE
Два блок «Сведения о связанных лицах» заменить одним «Сведения о физических лицах организации»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#10]
Тут много всего. 

А. Физлиц может быть несколько, поэтому нужно уметь добавлять/удалять 
Б. Поля и их описания. 
Надо сверить с текущей версткой. Если есть лишние, то удалить, если что-то меняется относительно текущей версии, то поменять. 

1. «Роль лица»: обязательное, чек-бокс 
Значения: [x] Акционер/учредитель  [x]  ЕИО  [x]  Бенифициар 
2. «Доля»: выводить, если выбрано “Акционер/учредитель”, обязательное 
3. «Должность»: выводить, если выбрано “ЕИО”, обязательное
4. «Фамилия» обязательное
5. «Имя» обязательное 
6. «Отчество»: обязательное
7. «ИНН»: обязательное, только цифры 12 штук (перепроверить длину)
8. «Телефон»: обязательное, маска
9. «Эл. почта»: обязательное, маска
10.  «Пол»: обязательное, радио 
Значения:  - Мужской       - Женский
11. «Гражданство»: обязательное, справочник стран, в котором первым значением должна стоять “Россия” 
Справочник взять в dadata (наверное)
12.  «Дата рождения»: обязательное. не календарь, а маска дд.мм.гггг
13. «Место рождения»: обязательное (просто текстовое поле, не справочник)
14.   «Тип документа, удостоверяющего личность» : обязательное  , селект
Значения:       
– Паспорт гражданина Российской Федерации (Код 21)
– Дипломатический паспорт, служебный паспорт, удостоверяющие личность гражданина РФ за пределами РФ (Код 22)
– Временное удостоверение личности гражданина РФ, выдаваемое на период оформления паспорта гражданина РФ (Код 26)
– Свидетельство о рождении гражданина РФ (для граждан РФ в возрасте до 14 лет) (Код 27)
– Иные документы, признаваемые документами, удостоверяющими личность гражданина РФ в соответствии с законодательством РФ (Код 28)
ЭТОТ СПРАВОЧНИК ПРЕДЛАГАЮ ЗАХАРДКОДИТЬ НА ФРОНТЕ. ЧТО ПЕРЕДАВАТЬ В JSON/Back УТОЧНИТЬ У КЛИЕНТА!
15. «Серия»: обязательное 
16. «Номер»: обязательное  
17. «Дата выдачи»: обязательное  дд.мм.гггг
18. «Кем выдан»: обязательное  - 
19. «Код подразделения » обязательное, есть для этого справочник (пример реализации тут на каком-то шаге https://feijoa-develop.moos.solutions/credits/start/)
20. «Страна проживания»: обязательное, справочник стран мира 
21. «Адрес регистрации»: обязательное, поиск адреса в dadata
22.«Адрес местонахождения совпадает с адресом регистрации»      - Да         - Нет
23. «Адрес местонахождения»: обязательное, поиск адреса в dadata. Если в предыдущем поле выбрано “Да”, то в UI не показываем, а на беке заполнить автоматически тем же значением, что в поле “Адрес регистрации”

**Comment by osintsev** [comment]
<img width="585" alt="Screenshot 2022-12-27 at 11 37 54" src="https://user-images.githubusercontent.com/5693096/209661098-4181777d-ade0-4337-85dd-be2eec344a04.png">
файлы тут больше не загружаем, убрать

**Comment by osintsev** [comment]
<img width="1172" alt="Screenshot 2022-12-27 at 11 39 07" src="https://user-images.githubusercontent.com/5693096/209661229-c29658df-1f4c-49da-88ed-041201a3aa94.png">

это все ненужно

**Comment by osintsev** [comment]
короче какой-то бардак в форме(( прошу перепроверить строго по ТЗ. нужно оставить только перечисленные поля

**Comment by osintsev** [comment]
<img width="249" alt="Screenshot 2022-12-27 at 11 40 37" src="https://user-images.githubusercontent.com/5693096/209661423-5b10c929-a7d6-46ed-a8fd-e97f5d333c31.png">
и вот это зачем? цифру надо убрать, а кнопку лучше назвать «удалить физлицо» и поставить ее в конце формы/блока

**Comment by ZorikovPasha** [comment]
Лишние поля убраны

**Comment by osintsev** [comment]
вроде все норм. я закрываю, может клиент что-то увидит
