### ISSUE TITLE
Блок «Учредители – юридические лица»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#11]
Вместо блока «Сведения о группе компаний» ставим блок «Учредители – юридические лица»

Вот макет версии для чата, делаем по аналогии https://rko-bot.spaaace.io/founders

а. учредителей может быть несколько (надо уметь добавлять и удалять)
б. выбор компании = dadata
в. поле «доля» должно быть коротким

**Comment by osintsev** [comment]
Важно! 
Форма должна выводиться, если клиент не является индивидуальным предпринимателем (ОПФ клиента не равна “Индивидуальный предприниматель” или ОКОПФ клиента не равен “50102”)

**Comment by osintsev** [comment]
блок правильный, но у ИП он не должен появляться

ИП или ООО приходит из дадаты скорее всего после выбора компании. можно еще у бекендеров уточнить, как они определяют

**Comment by ZorikovPasha** [comment]
Блок теперь скрывается если в названии компании есть аббревиатура `ИП`

**Comment by osintsev** [comment]
закрываю, про ИП в другом тикете написал
