### ISSUE TITLE
Блок «Структура органов управления»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#12]
В блоке «Структура органов управления»
Удаляем все, что есть сейчас. Осталяем 1 селект с 3 опциями 
– Общее собрание участников
– Единоличный исполнительный орган
– Иное

Весь блок появляется, если клиент не является индивидуальным предпринимателем (ОПФ клиента не равна “Индивидуальный предприниматель” или ОКОПФ клиента не равен “50102”)

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/209210609-29a18341-7b72-4fad-b111-18bbe591f9a9.png)

**Comment by osintsev** [comment]
блок появляется у ИП, а не должен

**Comment by ZorikovPasha** [comment]
Блок теперь скрывается если в названии компании есть аббревиатура `ИП`

**Comment by osintsev** [comment]
https://dadata.ru/api/find-party/ посмотри тут как разделены компании и ИП

# Юрлица
{
    "query": "7707083893",
    "type": "LEGAL"
}

# Индивидуальные предприниматели
{
    "query": "784806113663",
    "type": "INDIVIDUAL"
}

**Comment by ZorikovPasha** [comment]
исправил, теперь информация о том является ли компания ИП или нет, берется из поля `type`
