### ISSUE TITLE
Блок «Выгодоприобретатели»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#14]
1. Поменять радио на переключатель да/нет2. 
2. Если «Да», то появлеяется инпут «Укажите третьи лица, к выгоде которых действует компания»: текстовое поле до 255 символов, обязательное

<img width="632" alt="Screenshot 2022-12-21 at 10 39 20" src="https://user-images.githubusercontent.com/5693096/208885823-8981f968-fdf2-4b3f-8eca-4f044562f364.png">
<img width="428" alt="Screenshot 2022-12-21 at 10 39 30" src="https://user-images.githubusercontent.com/5693096/208885866-c9c7eb23-8773-4c55-99f2-dbf8095831cd.png">

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/209004950-3cfa4134-68d9-466a-b936-b7c738a157bf.png)
