### ISSUE TITLE
Блок «Отметьте все верные утверждения» обновить

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#16]
Блок «Отметьте все верные утверждения» переименовать на «Сведения о соответствии FATCA и и стратегическом значении компании (выберите все верные утверждения)»: 

чек-боксы   
[x] Юридическое лицо является Финансовым институтом в соответствии с Законом США «О налогообложении иностранных счетов» (FATCA) и/или главой 20.1 Налогового кодекса РФ 
[x] Юридическое лицо, или бенефициар, или выгодоприобретатель являются налоговым резидентом иностранного государства и/или у юридического лица, бенефициара или выгодоприобретателя отсутствует налоговое резидентство во всех государствах (территориях))   - Юридическое лицо имеет признаки Пассивной нефинансовой организации 
[x] Подтверждаю и гарантирую, что все Выгодоприобретатели/бенефициары индивидуального предпринимателя являются налогоплательщиками исключительно в РФ и, если выгодоприобретателем является юридическое лицо, то оно не имеет признаков Пассивной нефинансовой организации
[x] Юридическое лицо, выгодоприобретатель или бенефициар являются налоговым резидентом США
[x] Компания осуществляет виды деятельности, которые могут иметь стратегическое значение для оборонно-промышленного комплекса и безопасности РФ 
[x] Компания является хозяйственным обществом, имеющим стратегическое значение для оборонно-промышленного комплекса и безопасности РФ либо обществом, находящимся под его прямым или косвенным контролем, которые указаны в Федеральном законе от 21.07.2014 № 213-ФЗ      
[x] Компания не относится к указанным в настоящем пункте юридическим лицам

**Comment by osintsev** [comment]
Также поменять стиль заголовока и сворачиваемость – сделать как у всех остальных

<img width="648" alt="Screenshot 2022-12-21 at 11 00 31" src="https://user-images.githubusercontent.com/5693096/208889900-3ae5080c-102e-4873-896e-4e0944d001b9.png">

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/208990196-c9ca9607-5e8a-4d52-91af-c0db37b584d2.png)
![image](https://user-images.githubusercontent.com/86666268/208990228-213efcc5-1f5f-49b3-b392-de6d9b492592.png)
