### ISSUE TITLE
Добавить блок «Кодовое слово»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#18]
После блока с чекбоксами 

Добавить блок «Кодовое слово»
Там 1 инпут с валидацией 

– до 35 символов, символы кириллицы и ряд специальных символов
– АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя
– разрешен пробел

**Comment by ZorikovPasha** [comment]
ограничил длину ввода,

**Comment by osintsev** [comment]
Добавлено не в то место! 

Имел в виду другие чекбоксы 

>После блока с чекбоксами
<img width="1218" alt="Screenshot 2022-12-27 at 11 17 59" src="https://user-images.githubusercontent.com/5693096/209659034-9953afe5-0cde-427b-9226-7b9d69d241ea.png">

Заголовок должен быть большой как везде 
<img width="175" alt="Screenshot 2022-12-27 at 11 18 29" src="https://user-images.githubusercontent.com/5693096/209659080-f0b5c73c-e99e-40b2-af18-6c2bd6286ec5.png">

**Comment by ZorikovPasha** [comment]
убрано 
![image](https://user-images.githubusercontent.com/86666268/209692833-2f8b2aad-d169-4bb5-9efc-55ff0982b3ba.png)
добавлено 
![image](https://user-images.githubusercontent.com/86666268/209693154-309c9693-391d-435e-815d-bc3dd5c886e9.png)

**Comment by osintsev** [comment]
валидация не ругается на латиницу, там только кирилицу можно в поле

<img width="621" alt="Screenshot 2022-12-28 at 12 00 12" src="https://user-images.githubusercontent.com/5693096/209808964-fa1bc3c8-c9d2-4215-9bc9-08e1f9646a3b.png">

**Comment by ZorikovPasha** [comment]
Сделал валидацию, теперь допускается вводить только кириллицу
