### ISSUE TITLE
Новый блок «Загрузите документы»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#21]
Раньше файлы атачили в физлицах, теперь там этого нет. Их вынесли отдельно. Надо

1. После блока с физлицами сделать новый раздел «Загрузите документы»
2. Там три инпута для атача файлов 
- Документ,удостоверяющий личность единоличного исполнительного органа: обязательный, можно приложить несколько скринов 
- Документы,подтверждающие реальную деятельность: необязательный, можно приложить несколько скринов 
- Лицензии: необязательный, можно приложить несколько скринов

**Comment by osintsev** [comment]
1. плашку-кнопку «загрузить документ» давай растянем на всю ширину. текст по центру кнопки ставим
2. надо уметь удалять загруженные файлы (добавить крестик удаления)

**Comment by ZorikovPasha** [comment]
предлагаю использовать кнопку Удалить как и везде 
![image](https://user-images.githubusercontent.com/86666268/209720408-cb09d049-1acd-4d2f-97a9-23255f0aaa62.png)

**Comment by osintsev** [comment]
пусть пока так, потом отдельно переделаем дизайн
