### ISSUE TITLE
В тарифах после доп услуг добавить подписку на рассылку

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#22]
1. Добавить блок «Согласие на получение информационной рассылки» с переключателем да/нет. 
2. Разместить на форме следующий текст: “Заявитель дает согласие на получение им предложений, информации о продуктах/ услугах, рекламы и иной информации от Банка, Партнеров Банка по почте, по сетям электросвязи, в том числе путем контактов по телефону, электронной почте, с помощью СМС - сообщений и иными способами.”  
3. Переключатель должен быть установлен в положение “Да”. Клиент может выбрать значение “Нет”. 
<img width="576" alt="Screenshot 2022-12-21 at 11 23 53" src="https://user-images.githubusercontent.com/5693096/208894115-392f9c2a-f4e2-4ebc-a758-104fbf08670e.png">

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/208998435-78ab8ec3-f282-4da3-9b0f-e37349f14fcd.png)
![image](https://user-images.githubusercontent.com/86666268/208998457-ca4d8582-d935-4287-b7ff-4840465453e2.png)
![image](https://user-images.githubusercontent.com/86666268/208998512-9433e7c0-6666-4edf-b2e5-c1dd157d57d3.png)

**Comment by osintsev** [comment]
сейчас блок по умолчанию скрыт, поэтому переключатель не видно. прошу сделать наоборот, чтобы блок был по умолчанию развернут

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/209692551-8c435b15-070a-492f-85ea-fc59416f6f56.png)
