### ISSUE TITLE
Согласие на обработку даных обновить 

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#23]
<img width="1176" alt="Screenshot 2022-12-21 at 11 27 04" src="https://user-images.githubusercontent.com/5693096/208894737-2728d805-9778-4d1c-873c-92c7d04ecf64.png">

Этот блок 

В нем оставить текст: Нажимая на кнопку «Отправить», вы соглашаетесь с условиями подачи заявки и обработки персональных данных

и добавить кнопку/ссылку/стрелочку, которая развернет в этом блоке полный текст соглашения 

Согласие на обработку персональных данных
Настоящим Заявитель предоставляет КБ «Ренессанс Кредит» (ООО) (ОГРН 1027739586291, 115114, г. Москва, Кожевническая улица, д.14) (далее – Банк) согласие на обработку (совершение любых действий с использованием средств автоматизации или без, включая сбор, запись, систематизацию, накопление, хранение, уточнение, извлечение, использование, передачу, обезличивание, блокировку, удаление, уничтожение) Банком, Партнерами Банка и иными лицами, с которыми Банк заключит договоры на оказание услуг для исполнения обязательств Банка перед Клиентом в рамках Договоров на предоставление Услуги, путем осуществления контактов с помощью средств связи, всех своих персональных данных и/или своего фото- и/или видео изображения, и/или аудиозапись своего голоса в целях проверки достоверности
предоставленных им сведений, комплексной оценки своего финансового состояния, а также в целях продвижения услуг Банка и Партнеров Банка на рынке. Согласие действует в течение сроков хранения документов и сведений, содержащих персональные данные, установленных законодательством Российской Федерации, и может быть отозвано путем предоставления письменного заявления в Банк.

При возможности выводить согласие на использование ПЭП только если клиент является индивидуальным предпринимателем (ОПФ клиента = “Индивидуальный предприниматель” или ОКОПФ клиента =  “50102”)
Согласие на использование ПЭП
Настоящим Заявитель в соответствии со ст. 428 Гражданского кодекса Российской Федерации присоединяется к Соглашению об использовании простой электронной подписи физического лица (далее – Соглашение ПЭП ФЛ), подтверждает, что ознакомлен с Соглашением ПЭП ФЛ, опубликованным на Сайте Банка, выражает свое согласие с ним и обязуется его выполнять.

Согласие на обработку сведений об абоненте
Заявитель, являющийся пользователем номера мобильного телефона, указанного в настоящей Анкете, выражает согласие ПАО «Вымпел-Коммуникации» (ОГРН 1027700166636) (далее – Оператор) на обработку сведений о себе, как об абоненте, в том числе: о номере мобильного телефона, абонентском оборудовании (далее-Оборудование), о международном идентификаторе sim- карты, об изменениях номера мобильного телефона на sim-карте/ номера Оборудования/ номера абонентского договора, об оформлении номера мобильного телефона на иное лицо, о расторжении договора в отношении номера мобильного телефона/ перенесения номера мобильного телефона в сеть другого Оператора, приостановки/ возобновлении предоставления услуг на номере мобильного телефона, иные данные о номере мобильного телефона, об оказанных Оператором услугах связи (сведений об оплате услуг связи, идентификаторах, местонахождении Оборудования при оказании услуг связи) и передачу результата обработки Банку для проверки предоставленных Заявителем данных, а также для других законных целей. Согласие дано на срок до его отзыва.

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/208974830-41caee44-836c-4452-82a8-d613964f537d.png)
![image](https://user-images.githubusercontent.com/86666268/208974862-7ac0e6a5-4736-4c26-80d4-0f43780561bf.png)
