### ISSUE TITLE
Тарифы: добавить кнопку «выбрать позже»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#24]
На странице с тарифами у нас 3 варианта, но выбор тарифа необязательный. 

Надо под ними сделать серую кнопку по центру экрана «выбрать позже»

**Comment by ZorikovPasha** [comment]
Какова логика будет данной кнопки?

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/209184714-15ed8a56-09f5-4e59-8836-883e64f6328d.png)
![image](https://user-images.githubusercontent.com/86666268/209184825-7dd7f5b8-1061-4b66-9bae-f7fde7afb615.png)

**Comment by osintsev** [comment]
все норм!
