### ISSUE TITLE
Изменить блок "адреса"

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#7]
1) Убрать "фактический" тип адреса. Остаются только "юридический" и "почтовый"
2) Убрать поле "основание" совсем
3) инпут с адресом сделать длиннее, таким же как сейчас 2 инпута вместе (адрес + основание)
4) Напоминалка про dadata

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/209204325-06dbdb95-0cc4-43db-8f86-7333919a3824.png)
