### ISSUE TITLE
Добавить блок «Контакты»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-rko-frontend#8]
После блока «Реквизиты компании» добавить блок «Контакты»

- E-mail: маска [pochta@server.com]: обязательное поле
- Телефон: стандартная маска номера : обязательное поле
- Сайт компании: маска http:// необязательное
 - Факс: стандартная маска номера : необязательное

Названия полей посмотреть в задаче для бекендера https://github.com/SuperbCoders/F-telegram-bot-application/issues/4

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/209002569-855aec28-dbcf-46b5-b590-6d274c592a92.png)

**Comment by ZorikovPasha** [comment]
https://github.com/SuperbCoders/F-telegram-bot-RKO/issues/4

**Comment by osintsev** [comment]
давай в маске напишем www.
а то вдруг https кого-то напугает
валидация и то и то пропускает, просто надпись пусть будет более привычная

**Comment by ZorikovPasha** [comment]
![image](https://user-images.githubusercontent.com/86666268/209693896-f35a1eee-23ca-41c0-b488-25bc01fd50a7.png)

**Comment by ZorikovPasha** [comment]
Добавлена на наличие `https://` или `www.`
